---
#
#  Copyright (c) 2020 NetEase Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

install_with_deb: false
tmp_dir: /tmp/curve-ansible-tmp-files
local_mds_package_path: ../curve-mds
mds_remote_tmp_dir: /tmp/mds
mds_bin_dir: /usr/bin
mds_lib_dir: /usr/lib
mds_log_dir: /data/log/curve/mds
local_chunkserver_package_path: ../curve-chunkserver
chunkserver_bin_dir: /usr/bin
local_aws_sdk_package_path: ../aws-sdk
aws_sdk_lib_dir: /usr/lib
aws_sdk_include_dir: /usr/include
local_curve_sdk_package_path: ../curve-sdk
curve_sdk_bin_dir: /usr/bin
curve_sdk_lib_dir: /usr/lib
curve_sdk_include_dir: /usr/include
curve_sdk_curvefs_dir: /usr/curvefs
local_nebd_package_path: ../../nebd-package
nebd_bin_dir: /usr/bin
nebd_lib_dir: /usr/lib
local_nbd_package_path: ../../nbd-package
nbd_bin_dir: /usr/bin
snapshot_bin_dir: /usr/bin
snapshot_clone_server_log_dir: /data/log/curve/snapshotclone
snapshotcloneserver_bin_dir: /usr/bin
local_snapshotcloneserver_package_path: ../curve-snapshotcloneserver
snapshotcloneserver_lib_dir: /usr/lib

local_snapshotcloneserver_nginx_package_path: ../curve-nginx
snapshotcloneserver_nginx_dir: /etc/curve/nginx

local_tool_package_path: ../curve-tools
tool_bin_dir: /usr/bin


etcd_download_url: https://github.com/etcd-io/etcd/releases/download
etcd_version: v3.4.0
etcd_download_dir: /tmp
install_etcd_dir: /usr/bin

lib_download_dir: /tmp
libunwind_download_url: http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz
jemalloc_version: 3.6.0
jemalloc_download_url: https://github.com/jemalloc/jemalloc/releases/download/jemalloc-3.6.0.tar.bz2
