# load(
#     "//:copts.bzl",
#     "GCC_FLAGS",
#     "GCC_TEST_FLAGS"
#     )

# cc_test(
#         name = "snapshot_server_utest",
#         srcs = glob([
#             "*.cpp","*.h"
#         ],
#         ),
#         deps = ["//src/common/concurrent:curve_concurrent", "//external:gtest", "//src/snapshotcloneserver:snapshot_server_lib"],
#         copts = GCC_TEST_FLAGS
#         )

