#cc_test(
#    name = "curve_chunkserverStorage_unittest",
#    srcs = glob([
#        "*.cpp",
#    ]),
#    includes = ([]),
#    linkopts = ([
#        "-pthread",
#        "-std=c++11",
#        "-fPIC",
#        "-DGFLAGS_NS=google",
#    ]),
#    defines = ["UNIT_TEST"],
#    deps = [
#        "//external:braft",
#        "//external:gflags",
#        "//external:gtest",
#        "//include:include-common",
#        "//include/chunkserver:include-chunkserver",
#        "//src/chunkserver/chunkserverStorage:chunkserver-sfsadaptor-lib",
#        "//src/sfs:chunkserver-sfsmock-lib",
#    ],
#)
