# etcd version: etcd Version: 3.4.0-rc.1
# Go version: go1.12.8
# grpc version: grpc1.23.0
cc_library(
    name = "etcdclientlib",
    srcs = ["libetcdclient.so"],
    hdrs = ["etcdclient.h"],
    visibility = ["//visibility:public"],
)
