---
- hosts: "{{ hosts }}"
  roles:
    - { role: common }
  vars_files:
    - vars/main.yml
    - vars/client.yml

  tasks:
    - name: mount fs
      shell: "{{ project_mount_command | echo('mount command:') }}"
      tags: [mount]

    - name: umount fs
      shell:
        sudo curvefs_tool umountfs
        -mdsAddr={{ groups.mds | join_peer(hostvars, "mds_listen_port") }}
        -mountpoint={{ ansible_hostname }}:{{ curvefs_client_mount_path }}
        -fsname={{ curvefs_client_mount_fsname }}
      tags: [umount]
