language: c++
sudo: required
services:
  - docker
    #before_install: sudo apt-get install fio -y
intall: 
  - sudo docker pull chenyunhui/untest:1.0.0
script:
  - sudo docker run -d --privileged --name curve --volume ~/opencurve/curve:/curve chenyunhui/untest:1.0.0 /bin/bash /etc/rc.local 
  - sudo docker exec -it curve  /bin/bash -c "cd /curve/  && bash untest.sh"
