{
 "title": "Client",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "客户端",
    "query": "label_values({__name__=~\"curve_client.*\", instance=~\".*:90.*\"}, instance)"
   },
   {
    "name": "file",
    "label": "文件",
    "query": "{__name__=~\"curve_client.*write_qps\", instance=~\"$client\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "进程资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "客户端运行时间",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime{instance=~\"$client\"}"
      }
     ]
    },
    {
     "title": "client_cpu_usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{instance=~\"$client\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "客户端配置",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "客户端配置",
     "type": "table",
     "description": "客户端的配置情况",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{__name__=~\"curve_client_config.*\", instance=~\"$client\"}"
      }
     ]
    }
   ]
  },
  { "title": "用户接口层指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "client_read_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_read_qps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_write_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_write_qps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_read_rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_read_rps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_write_rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_write_rps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_read_bps",
   "type": "graph",
   "description": "client用户接口层统计到的每秒读取字节数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_read_bps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_write_bps",
   "type": "graph",
   "description": "client用户接口层统计到的每秒写入字节数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_write_bps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_read_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_.*read_lat_latency\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_write_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_.*write_lat_latency\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "write_io_size_percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"curve_client_[[file:regex]]_write_request_size_recoder_latency.*\", instance=~\"$client\"}, \"__name__\", \"$1 write_request_size$2\", \"__name__\", \"curve_client_(.*)_write.*latency(.*)\")",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "中间业务层指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "inflight_rpc_num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_inflight_rpc_num\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "get_leader_retry_rpc",
   "type": "graph",
   "description": "每秒get leader的重试rpc次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"curve_client_[[file:regex]]_.*retry_rpc\", instance=~\"$client\"}, \"file\", \"$1\", \"__name__\", \"curve_client_(.*)_get_leader_retry_rpc\")",
     "legendFormat": "{{file}}"
    }
   ]
  },
  { "title": "rpc层指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "read_rpc_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_.*read_rpc_qps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "write_rpc_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_.*write_rpc_qps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "read_rpc_bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_.*read_rpc_bps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "write_rpc_bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_.*write_rpc_bps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "read_rpc_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_.*read_rpc_lat_latency\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "write_rpc_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_.*write_rpc_lat_latency\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "timeout_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_[[file:regex]]_.*timeout_qps\", instance=~\"$client\"}"
    }
   ]
  },
  { "title": "与MDS通信指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "client2mds_rpc_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_mds_client_.*lat_qps\"}"
    }
   ]
  }
 ]
}