{
 "title": "MDS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "主机",
    "query": "rpc_server_6666_curve_mds_curve_fsservice_create_file"
   },
   {
    "name": "lpmetric",
    "query": "{__name__=~\"topology_metric_logical_pool_.*\"}"
   }
  ]
 },
 "panels": [
  { "title": "进程资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "进程运行时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "进程cpu使用情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage {{instance}}"
    },
    {
     "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_system {{instance}}"
    },
    {
     "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_user {{instance}}"
    }
   ]
  },
  {
   "title": "内存占用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_virtual{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "逻辑池状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "logical_pool_metrics",
     "type": "table",
     "description": "逻辑池监控指标",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_logical_pool_.*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "chunkserver状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "chunkserver_leader_num_series",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_chunkserver_id_.*_leadernum\"}"
      }
     ]
    },
    {
     "title": "chunkserver_current_leader_count",
     "type": "graph",
     "description": "所有chunkserver当前的leader count",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_chunkserver_id_.*_leadernum\"}"
      }
     ]
    },
    {
     "title": "chunkserver_current_copyset_number",
     "type": "graph",
     "description": "所有chunkserver当前的copyset数量",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_chunkserver_id_.*_copysetnum\"}"
      }
     ]
    },
    {
     "title": "chunkserver_current_scatterwidth",
     "type": "graph",
     "description": "所有chunkserver当前的scatterwidth",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_chunkserver_id_.*_scatterwidth\"}"
      }
     ]
    },
    {
     "title": "chunkserver_current_write_bps",
     "type": "graph",
     "description": "所有chunkserver当前的rpc层写请求速率",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_chunkserver_id_.*_write_rate\"}"
      }
     ]
    },
    {
     "title": "chunkserver_current_write_iops",
     "type": "graph",
     "description": "所有chunkserver当前的rpc层写请求iops",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_chunkserver_id_.*_write_iops\"}"
      }
     ]
    },
    {
     "title": "chunkserver_current_read_bps",
     "type": "graph",
     "description": "所有chunkserver当前的rpc层读请求速率",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_chunkserver_id_.*_read_rate\"}"
      }
     ]
    },
    {
     "title": "chunkserver_current_read_iops",
     "type": "graph",
     "description": "所有chunkserver当前的rpc层读请求iops",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_chunkserver_id_.*_read_iops\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "调度监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "operator_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mds_scheduler_metric_operator_num"
      }
     ]
    },
    {
     "title": "add_peer_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mds_scheduler_metric_add_peer_num"
      }
     ]
    },
    {
     "title": "transfer_leader_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mds_scheduler_metric_transfer_leader_num"
      }
     ]
    },
    {
     "title": "remove_peer_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mds_scheduler_metric_remove_peer_num"
      }
     ]
    },
    {
     "title": "normal_operator_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mds_scheduler_metric_normal_operator_num"
      }
     ]
    },
    {
     "title": "high_operator_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mds_scheduler_metric_high_operator_num"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC层指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "total_rpc_qps",
     "type": "graph",
     "description": "所有rpc请求的qps",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"rpc_server_.*_curve_mds_.*_qps\", instance=~\"$instance\"})",
       "legendFormat": "{{total_rpc_qps_ { instance=$instance}}}"
      }
     ]
    },
    {
     "title": "total_rpc_concurrency",
     "type": "graph",
     "description": "当前MDS上所有inflight的rpc请求个数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"rpc_server_.*_curve_mds_.*_concurrency\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "request_rpc_qps",
     "type": "graph",
     "description": "各请求rpc的qps",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_mds_.*_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "request_rpc_lat",
     "type": "graph",
     "description": "MDS各rpc请求的latency",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"rpc_server_.*_curve_mds_.*_sum\", instance=~\"$instance\"}, \"method\", \"$1\", \"__name__\", \"rpc_server_.*_curve_mds_(.*)_sum\") / label_replace({__name__=~\"rpc_server_.*_curve_mds_.*_count\", instance=~\"$instance\"}, \"method\", \"$1\", \"__name__\", \"rpc_server_.*_curve_mds_(.*)_count\")",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HeartBeat指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "heartbeat_qps",
     "type": "graph",
     "description": "每秒成功处理的heartbeat个数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_mds_heartbeat_heartbeat_service_chunk_server_heartbeat_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "heartbeat_concurrency",
     "type": "graph",
     "description": "heartbeat当前inflight的请求个数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_mds_heartbeat_heartbeat_service_chunk_server_heartbeat_concurrency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "heartbeat_lat_avg",
     "type": "graph",
     "description": "heartbeat请求平均延时",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_mds_heartbeat_heartbeat_service_chunk_server_heartbeat_sum\", instance=~\"$instance\"} / {__name__=~\"rpc_server_.*_curve_mds_heartbeat_heartbeat_service_chunk_server_heartbeat_count\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "heartbeat_lat_percentile",
     "type": "graph",
     "description": "heartbeat请求延时分位图",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_mds_heartbeat_heartbeat_service_chunk_server_heartbeat\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}