{
 "title": "Report",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chunkserver",
    "query": "{__name__=~\"process_cpu_usage\", job=~\"chunkserver\"}"
   },
   {
    "name": "client",
    "query": "{__name__=~\"process_cpu_usage\", job=~\"client\"}"
   },
   {
    "name": "mds",
    "query": "{__name__=~\"process_cpu_usage\", job=~\"mds\"}"
   }
  ]
 },
 "panels": [
  { "title": "MDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "mds_cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$mds\"}",
     "legendFormat": "process_cpu_usage {{instance}}"
    },
    {
     "expr": "process_cpu_usage_system{instance=~\"$mds\"}",
     "legendFormat": "process_cpu_usage_system {{instance}}"
    },
    {
     "expr": "process_cpu_usage_user{instance=~\"$mds\"}",
     "legendFormat": "process_cpu_usage_user {{instance}}"
    }
   ]
  },
  {
   "title": "mds_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_virtual{instance=~\"$mds\"}"
    }
   ]
  },
  {
   "title": "copysetnum_metrics",
   "type": "table",
   "description": "copyset数量监控指标",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{__name__=~\"topology_metric_logical_pool_.*copysetnum.*\"}"
    }
   ]
  },
  {
   "title": "leadernum_metrics",
   "type": "table",
   "description": "leader数量监控指标",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{__name__=~\"topology_metric_logical_pool_.*leadernum.*\"}"
    }
   ]
  },
  {
   "title": "scatterwidth_metric",
   "type": "table",
   "description": "scatterwidth指标",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{__name__=~\"topology_metric_logical_pool_.*scatterwidth.*\"}"
    },
    {}
   ]
  },
  {
   "title": "request_rpc_lat",
   "type": "graph",
   "description": "MDS各rpc请求的latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"rpc_server_.*_curve_mds_.*_sum\", instance=~\"$mds\"}, \"method\", \"$1\", \"__name__\", \"rpc_server_.*_curve_mds_(.*)_sum\") / label_replace({__name__=~\"rpc_server_.*_curve_mds_.*_count\", instance=~\"$mds\"}, \"method\", \"$1\", \"__name__\", \"rpc_server_.*_curve_mds_(.*)_count\")",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "request_rpc_qps",
   "type": "graph",
   "description": "各请求rpc的qps",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"rpc_server_.*_curve_mds_.*_qps\", instance=~\"$mds\"}"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "client_read_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_.*_.*read_lat_latency\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_read_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_.*_read_qps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_read_bps",
   "type": "graph",
   "description": "client用户接口层统计到的每秒读取字节数",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_.*_read_bps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_write_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_.*_.*write_lat_latency\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_write_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_.*_write_qps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_write_bps",
   "type": "graph",
   "description": "client用户接口层统计到的每秒写入字节数",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_.*_write_bps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client2mds_rpc_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_mds_client_.*lat_qps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "get_leader_retry_rpc",
   "type": "graph",
   "description": "每秒get leader的重试rpc次数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"curve_client_.*_.*retry_rpc\", instance=~\"$client\"}, \"file\", \"$1\", \"__name__\", \"curve_client_(.*)_get_leader_retry_rpc\")",
     "legendFormat": "{{file}}"
    }
   ]
  },
  {
   "title": "timeout_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curve_client_.*_.*timeout_qps\", instance=~\"$client\"}"
    }
   ]
  },
  {
   "title": "client_write_normalized_latency",
   "type": "graph",
   "description": "client单位大小的平均latency",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none", "label": "us/kb" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"curve_client_.*_.*write_lat_latency\", instance=~\"$client\"}, \"filename\", \"$1\", \"__name__\", \"curve_client_(.*)_write.*latency\") / (label_replace({__name__=~\"curve_client_.*_write_request_size_recoder_latency\", instance=~\"$client\"}, \"filename\", \"$1\", \"__name__\", \"curve_client_(.*)_write.*latency\") / 1024)"
    }
   ]
  },
  { "title": "Chunkserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "chunkserver_cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$chunkserver\"}",
     "legendFormat": "cpu_usage {{instance}}"
    },
    {
     "expr": "process_cpu_usage_system{instance=~\"$chunkserver\"}",
     "legendFormat": "cpu_usage_system{{instance}}"
    },
    {
     "expr": "process_cpu_usage_user{instance=~\"$chunkserver\"}",
     "legendFormat": "cpu_usage_user {{instance}}"
    }
   ]
  },
  {
   "title": "iobuf_memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "iobuf_block_memory{instance=~\"$chunkserver\"}",
     "legendFormat": "iobuf_block_memory {{instance}}"
    }
   ]
  },
  {
   "title": "chunkfilepool_left_chunks",
   "type": "graph",
   "description": "chunkfilepool中剩余的chunk的数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"chunkserver_.*_chunkfilepool_left\", instance=~\"$chunkserver\"}) by (instance)",
     "legendFormat": "chunkfilepool_left_chunks {{instance}}"
    }
   ]
  },
  {
   "title": "total_chunk_num",
   "type": "graph",
   "description": "chunkserver上所有已分配的chunk的数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"chunkserver_.*_chunk_count\", instance=~\"$chunkserver\"}",
     "legendFormat": "total_chunk_num {{instance}}"
    },
    {}
   ]
  },
  {
   "title": "write_chunk_iops",
   "type": "graph",
   "description": "chunk service层面每秒成功处理的write chunk个数",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"chunkserver_.*_write_iops\", instance=~\"$chunkserver\"}"
    },
    {}
   ]
  },
  {
   "title": "write_bps",
   "type": "graph",
   "description": "chunkserver service层面每秒成功write chunk的字节数",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"chunkserver_.*_write_bps\", instance=~\"$chunkserver\"}",
     "legendFormat": "write_bps {{instance}}"
    }
   ]
  },
  {
   "title": "write_chunk_concurrency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk_concurrency\", instance=~\"$chunkserver\"}",
     "legendFormat": "{{write_chunk_concurrency}} {{instance}}"
    }
   ]
  },
  {
   "title": "read_chunk_iops",
   "type": "graph",
   "description": "chunk service层面每秒成功处理的read chunk个数",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"chunkserver_.*_read_iops\", instance=~\"$chunkserver\"}) by (instance)",
     "legendFormat": "read_chunk_iops {{instance}}"
    }
   ]
  },
  {
   "title": "read_bps",
   "type": "graph",
   "description": "chunkserver service层面每秒成功read chunk的字节数",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"chunkserver_.*_read_bps\", instance=~\"$chunkserver\"}",
     "legendFormat": "read_bps {{instance}}"
    }
   ]
  },
  {
   "title": "read_chunk_concurrency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_read_chunk_concurrency\", instance=~\"$chunkserver\"}",
     "legendFormat": "{{read_chunk_concurrency}} {{insgance}}"
    }
   ]
  },
  {
   "title": "avg_read_nomalized_lat",
   "type": "graph",
   "description": "chunkserver read chunk 单位大小内的平均延时",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "none", "label": "us/kb" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"chunkserver_.*_read_lat_latency\", instance=~\"$chunkserver\"} / ({__name__=~\"chunkserver.*_read_io_size_latency\", instance=~\"$chunkserver\"}/1024)",
     "legendFormat": "avg_read_nomalized_lat {{instance}}"
    }
   ]
  },
  {
   "title": "avg_write_nomalized_lat",
   "type": "graph",
   "description": "chunkserver write chunk 单位大小内的平均延时",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "none", "label": "us/kb" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"chunkserver_.*_write_lat_latency\", instance=~\"$chunkserver\"} / ({__name__=~\"chunkserver.*_write_io_size_latency\", instance=~\"$chunkserver\"}/1024)",
     "legendFormat": "avg_write_nomalized_lat {{instance}}"
    }
   ]
  },
  { "title": "Raft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "raft_send_entries_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "raft_send_entries_latency{instance=~\"$chunkserver\"}",
     "legendFormat": "raft_send_entries_latency {{instance}}"
    }
   ]
  },
  {
   "title": "raft_send_entries_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "raft_send_entries_qps{instance=~\"$chunkserver\"}",
     "legendFormat": "raft_send_entries_qps {{instance}}"
    }
   ]
  },
  {
   "title": "raft_service_append_entries_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"rpc_server_.*_braft_raft_service_append_entries_sum\", instance=~\"$chunkserver\"} / {__name__=~\"rpc_server_.*_braft_raft_service_append_entries_count\", instance=~\"$chunkserver\"}",
     "legendFormat": "raft_service_append_entries_latency {{instance}} avg"
    }
   ]
  },
  {
   "title": "raft_service_append_entries_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"rpc_server_.*_braft_raft_service_append_entries_qps\", instance=~\"$chunkserver\"}",
     "legendFormat": "raft_service_append_entries_qps {{instance}}"
    }
   ]
  },
  {
   "title": "storage_append_entries_latency",
   "type": "graph",
   "description": "raft日志落盘的延时",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "raft_storage_append_entries_latency{instance=~\"$chunkserver\"}",
     "legendFormat": "raft_storage_append_entries_latency {{instance}}"
    }
   ]
  },
  {
   "title": "raft_num_log_entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "raft_num_log_entries{instance=~\"$chunkserver\"}",
     "legendFormat": "raft_num_log_entries {{instance}}"
    },
    { "expr": "raft_num_log" }
   ]
  },
  {
   "title": "install_snapshot_bps",
   "type": "graph",
   "description": "安装快照的数据流量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "raft_install_snapshot_bps{instance=~\"$chunkserver\"}",
     "legendFormat": "raft_storage_append_entries_latency {{instance}}"
    }
   ]
  }
 ]
}