#!/bin/bash

set -e

chown -R root:root /data/nebd
chown -R root:root /data/log/nebd

chmod -R 777 /data/nebd
chmod -R 777 /data/log/nebd

systemctl daemon-reload
systemctl enable nebd-daemon.service
systemctl start nebd-daemon.service

exit 0