.PHONY: build

curve-sdk:
	docker build --target  curve-tgt -t opencurvedocker/curve-base:curve-tgt-openeuler .

build:
	docker build --target  curve-tgt -t opencurvedocker/curve-base:curve-tgt-openeuler .
