{
 "title": "ChunkServer",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "主机",
    "query": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk\"}"
   },
   {
    "name": "instance",
    "label": "实例",
    "query": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
   },
   {
    "name": "ip",
    "label": "IP",
    "query": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk\", hostname=~\"$host\"}"
   },
   {
    "name": "port",
    "label": "端口号",
    "query": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk\", instance=~\"$ip.*\"}"
   },
   {
    "name": "copyset",
    "label": "copyset",
    "query": "{__name__=~\"copyset_.*_read_bps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "进程资源占用",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "进程运行时间",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      },
      {
       "expr": "process_cpu_usage_system{instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      },
      {
       "expr": "process_cpu_usage_user{instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "chunkserver配置",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "chunkserver配置",
     "type": "table",
     "description": "chunkserver的配置",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_config_.*\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "rpc层读写指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "total_rpc_qps",
     "type": "graph",
     "description": "chunkserver上所有rpc的每秒处理成功的请求个数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"rpc_server_.*_qps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "total_rpc_qps [[instance]]"
      }
     ]
    },
    {
     "title": "iobuf_memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "iobuf_block_memory{instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "read_chunk_eps",
     "type": "graph",
     "description": "read_chunk每秒在rpc层面的错误个数",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_read_chunk_eps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "read_chunk_concurrency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_read_chunk_concurrency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "read_chunk_qps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_read_chunk_qps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "write_chunk_eps",
     "type": "graph",
     "description": "write_chunk每秒在rpc层面的错误个数",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk_eps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "write_chunk_concurrency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk_concurrency\", instance=~\"([[ip:pipe]]):([[port:pipe]])\"}"
      }
     ]
    },
    {
     "title": "write_chunk_qps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk_qps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "avg_read_lat",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_read_chunk_sum\", instance=~\"([[ip:pipe]]):[[port:regex]]\"} / {__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_read_chunk_count\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "read_chunk_lat_percentile",
     "type": "graph",
     "description": "rpc层面read chunk延时的分位值",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_read_chunk\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "read_chunk_latency-{{quantile}} {{instance}}"
      }
     ]
    },
    {
     "title": "avg_write_lat",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk_sum\", instance=~\"([[ip:pipe]]):[[port:regex]]\"} / {__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk_count\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "write_chunk_lat_percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_curve_chunkserver_chunk_service_write_chunk\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "chunkserver层读写指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_chunk_eps",
     "type": "graph",
     "description": "read_chunk每秒在chunk service层面的错误个数",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"chunkserver_.*_read_eps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "read_chunk_eps {{instance}}"
      }
     ]
    },
    {
     "title": "read_chunk_iops",
     "type": "graph",
     "description": "chunk service层面每秒成功处理的read chunk个数",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"chunkserver_.*_read_iops\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "read_chunk_iops {{instance}}"
      }
     ]
    },
    {
     "title": "read_chunk_rps",
     "type": "graph",
     "description": "chunk service层面每秒接收到的read_chunk请求个数",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"chunkserver_.*_read_rps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "read_chunk_rps {{instance}}"
      }
     ]
    },
    {
     "title": "write_chunk_eps",
     "type": "graph",
     "description": "chunk service层面write_chunk每秒返回错误的请求个数",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"chunkserver_.*_write_eps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "write_chunk_eps {{instance}}"
      }
     ]
    },
    {
     "title": "write_chunk_iops",
     "type": "graph",
     "description": "chunk service层面每秒成功处理的write chunk个数",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_write_iops\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      },
      {}
     ]
    },
    {
     "title": "write_chunk_rps",
     "type": "graph",
     "description": "chunk service层面每秒接收到的write_chunk请求个数",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"chunkserver_.*_write_rps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "write_chunk_rps {{instance}}"
      }
     ]
    },
    {
     "title": "read_io_latency_percentile",
     "type": "graph",
     "description": "chunkserver service层面read chunk延时的分位值",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"chunkserver.*_read_lat_max_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}, \"__name__\", \"read_latency_max\", \"__name__\", \".*\")",
       "legendFormat": "{{__name__}} {{instance}} "
      },
      {}
     ]
    },
    {
     "title": "write_io_latency_percentile",
     "type": "graph",
     "description": "chunkserver service层面write chunk延时的分位值",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"chunkserver.*_write_lat_max_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}, \"__name__\", \"write_latency_max\", \"__name__\", \".*\")",
       "legendFormat": "{{__name__}} {{instance}} "
      }
     ]
    },
    {
     "title": "avg_read_lat",
     "type": "graph",
     "description": "chunkserver service层面的read chunk的平均延时",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_read_lat_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "read_latency {{instance}}"
      }
     ]
    },
    {
     "title": "avg_write_lat",
     "type": "graph",
     "description": "chunkserver service层面的write chunk的平均延时",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_write_lat_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "write_latency {{instance}}"
      }
     ]
    },
    {
     "title": "read_bps",
     "type": "graph",
     "description": "chunkserver service层面每秒成功read chunk的字节数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_read_bps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "read_bps {{instance}}"
      }
     ]
    },
    {
     "title": "write_bps",
     "type": "graph",
     "description": "chunkserver service层面每秒成功write chunk的字节数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_write_bps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "write_bps {{instance}}"
      }
     ]
    },
    {
     "title": "read_io_size_percentile",
     "type": "graph",
     "description": "chunkserver service层面read chunk的io大小的分位值",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ]
    },
    {
     "title": "write_io_size_percentile",
     "type": "graph",
     "description": "chunkserver service层面write chunk的io大小的分位值",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"chunkserver.*_write_io_size_max_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}, \"__name__\", \"write_io_size_max\", \"__name__\", \".*\")",
       "legendFormat": "{{__name__}} {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "快照克隆相关指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "recover_chunk_eps",
     "type": "graph",
     "description": "recover_chunk每秒在chunk service层面的错误个数",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_recover_eps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "recover_chunk_eps {{instance}}"
      }
     ]
    },
    {
     "title": "recover_chunk_iops",
     "type": "graph",
     "description": "chunk service层面每秒成功处理的recover chunk个数",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_recover_iops\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "recover_chunk_iops {{instance}}"
      }
     ]
    },
    {
     "title": "recover_chunk_rps",
     "type": "graph",
     "description": "chunk service层面每秒接收到的recover_chunk请求个数",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_recover_rps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "recover_chunk_rps {{instance}}"
      }
     ]
    },
    {
     "title": "avg_recover_lat",
     "type": "graph",
     "description": "chunkserver service层面的recover chunk的平均延时",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_recover_lat_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "recover_bps",
     "type": "graph",
     "description": "chunkserver service层面每秒成功recover chunk的字节数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_recover_bps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "recover_bps {{instance}}"
      }
     ]
    },
    {
     "title": "recover_io_latency_percentile",
     "type": "graph",
     "description": "chunkserver service层面recover chunk延时的分位值",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_recover_lat_latency_.*\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}} "
      }
     ]
    },
    {
     "title": "recover_io_size_percentile",
     "type": "graph",
     "description": "chunkserver service层面recover chunk的io大小的分位值",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_recover_io_size_latency.*\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "download_eps",
     "type": "graph",
     "description": "chunkserver从源下载数据请求每秒的错误个数",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_download_eps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "download_eps {{instance}}"
      }
     ]
    },
    {
     "title": "download_iops",
     "type": "graph",
     "description": "chunkserver从源下载数据的iops",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_download_iops\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "download_iops {{instance}}"
      }
     ]
    },
    {
     "title": "download_bps",
     "type": "graph",
     "description": "chunkserver从源下载数据的吞吐",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 101 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_download_bps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "download_bps {{instance}}"
      }
     ]
    },
    {
     "title": "paste_eps",
     "type": "graph",
     "description": "chunkserver将下载的数据paste到本地的每秒错误个数",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_paste_eps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "paste_eps {{instance}}"
      }
     ]
    },
    {
     "title": "paste_iops",
     "type": "graph",
     "description": "chunkserver将下载下来的数据paste到本地的iops",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 108 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_paste_iops\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "paste_iops {{instance}}"
      }
     ]
    },
    {
     "title": "paste_bps",
     "type": "graph",
     "description": "chunkserver将下载数据paste到本地的吞吐",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 108 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_download_bps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "paste_bps {{instance}}"
      }
     ]
    },
    {
     "title": "avg_download_lat",
     "type": "graph",
     "description": "chunkserver service层面的download 远端数据的平均延时",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 115 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_download_lat_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "avg_paste_lat",
     "type": "graph",
     "description": "chunkserver service层面的paste chunk的平均延时",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 115 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"chunkserver_.*_paste_lat_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "copyset指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "slected copyset count",
     "type": "singlestat",
     "description": "选中的copyset的数量",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count({__name__=~\"copyset_[[copyset:regex]]_datastore_chunk_count\", instance=~\"([[ip:pipe]]):[[port:regex]]\"})"
      }
     ]
    },
    {
     "title": "slected copyset chunk sum",
     "type": "singlestat",
     "description": "选中的copyset的chunk数量的总和",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_[[copyset:regex]]_datastore_chunk_count\", instance=~\"([[ip:pipe]]):[[port:regex]]\"})",
       "legendFormat": "seletced copyset chunk sum"
      }
     ]
    },
    {
     "title": "copyset_chunk_num",
     "type": "graph",
     "description": "各copyset上已分配的chunk的数量",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"copyset_[[copyset:regex]]_datastore_chunk_count\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}, \"__name__\", \"$1\", \"__name__\", \"copyset_(.*)_datastore_.*\")",
       "legendFormat": "copyset_chunk_num {{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "copyset_read_chunk_eps",
     "type": "graph",
     "description": "copyset层面每秒出错的read chunk请求个数",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_[[copyset:regex]].*_read_eps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "copyset_read_chunk_iops",
     "type": "graph",
     "description": "copyset层面每秒成功处理的read chunk个数",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_[[copyset:regex]].*_read_iops\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "copyset_read_chunk_rps",
     "type": "graph",
     "description": "copyset层面每秒接收到的read chunk请求个数",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_[[copyset:regex]].*_read_rps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "copyset_write_chunk_eps",
     "type": "graph",
     "description": "copyset层面每秒出错的write chunk请求个数",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_[[copyset:regex]].*_write_eps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "copyset_write_chunk_iops",
     "type": "graph",
     "description": "copyset层面每秒成功处理的write chunk个数",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_[[copyset:regex]].*_write_iops\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "copyset_write_chunk_rps",
     "type": "graph",
     "description": "copyset层面每秒接收到的write chunk请求个数",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_[[copyset:regex]].*_write_rps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "copyset_read_chunk_bps",
     "type": "graph",
     "description": "copyset层面每秒成功read chunk的字节数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_[[copyset:regex]].*_read_bps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "copyset_write_chunk_bps",
     "type": "graph",
     "description": "copyset层面每秒成功write chunk的字节数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_[[copyset:regex]].*_write_bps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "copyset_avg_read_lat",
     "type": "graph",
     "description": "copyset层面的read chunk的平均延时",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"copyset_[[copyset:regex]]_read_lat_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}, \"__name__\", \"$1\", \"__name__\", \"copyset_(.*)_read.*\")",
       "legendFormat": "copyset_{{__name__}}_read_latency {{instance}} "
      }
     ]
    },
    {
     "title": "copyset_avg_write_lat",
     "type": "graph",
     "description": "copyset层面的write chunk的平均延时",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"copyset_[[copyset:regex]]_write_lat_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}, \"__name__\", \"$1\", \"__name__\", \"copyset_(.*)_write.*\")",
       "legendFormat": "copyset_{{__name__}}_write_latency {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "chunkserver关键指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "total_chunk_num",
     "type": "graph",
     "description": "chunkserver上所有已分配的chunk的数量（包括clone chunk，不包括snapshot chunk）",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ]
    },
    {
     "title": "total_snapshot_chunk_num",
     "type": "graph",
     "description": "chunkserver上所有已分配的snapshot chunk的数量",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*snapshot_count\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "total_snapshot_chunk_num {{instance}}"
      }
     ]
    },
    {
     "title": "total_clone_chunk_num",
     "type": "graph",
     "description": "chunkserver上所有已分配的clone chunk的数量",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"copyset_.*_clonechunk_count\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "total_clonechunk_num {{instance}}"
      }
     ]
    },
    {
     "title": "chunkfilepool_left_chunks",
     "type": "graph",
     "description": "chunkfilepool中剩余的chunk的数量",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"chunkserver_.*_chunkfilepool_left\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "chunkfilepool_left_chunks {{instance}}"
      }
     ]
    },
    {
     "title": "chunk size in trash",
     "type": "graph",
     "description": "回收站中的chunk的数量",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"chunkserver_.*_chunk_trashed\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}) by (instance)",
       "legendFormat": "chunkfilepool_left_chunks {{instance}}"
      }
     ]
    },
    {
     "title": "copyset_count",
     "type": "graph",
     "description": "chunkserver上copyset的数量",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ]
    }
   ]
  },
  {
   "title": "Raft关键指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "raft_apply_tasks_batch_counter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "raft_apply_tasks_batch_avg_counter{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "raft_send_entries_batch_counter",
     "type": "graph",
     "description": "send entries接口每次请求的LogEntry个数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_send_entries_batch_avg_counter\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "raft_send_entries_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "raft_send_entries_latency{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "raft_send_entries_latency {{instance}}"
      }
     ]
    },
    {
     "title": "raft_send_entries_qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "raft_send_entries_qps{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "raft_send_entries_qps {{instance}}"
      }
     ]
    },
    {
     "title": "raft_service_append_entries_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_braft_raft_service_append_entries_sum\", instance=~\"([[ip:pipe]]):[[port:regex]]\"} / {__name__=~\"rpc_server_.*_braft_raft_service_append_entries_count\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "raft_service_append_entries_latency {{instance}} avg"
      }
     ]
    },
    {
     "title": "raft_service_append_entries_qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_braft_raft_service_append_entries_qps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "raft_service_append_entries_qps {{instance}}"
      }
     ]
    },
    {
     "title": "storage_append_entries_normalized_latency",
     "type": "graph",
     "description": "raft日志落盘时平均每kb数据写入的延时",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "us/kb" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_storage_append_entries_normalized_latency\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "storage_append_entries_latency",
     "type": "graph",
     "description": "raft日志落盘的延时",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "raft_storage_append_entries_latency{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "raft_storage_append_entries_latency {{instance}}"
      }
     ]
    },
    {
     "title": "raft_storage_flush_batch_counter",
     "type": "graph",
     "description": "raft每次刷日志时的batch大小",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_storage_flush_batch_.*counter.*\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "raft_get_file_qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_braft_file_service_get_file_qps\", instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "get_file_qps {{instance}}"
      }
     ]
    },
    {
     "title": "raft_num_log_entries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "raft_num_log_entries{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "raft_num_log_entries {{instance}}"
      }
     ]
    },
    {
     "title": "follower_install_snapshot_task_num",
     "type": "graph",
     "description": "follower正在下载快照的任务数量（一个copyset最多一个任务）",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "raft_follower_install_snapshot_task_num{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "raft_storage_append_entries_latency {{instance}}"
      }
     ]
    },
    {
     "title": "raft_install_snapshot_qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_braft_raft_service_install_snapshot_qps\"}"
      },
      {}
     ]
    },
    {
     "title": "leader_need_install_snapshot_task_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "raft_leader_need_install_snapshot_task_num{instance=~\"([[ip:pipe]]):[[port:regex]]\"}"
      }
     ]
    },
    {
     "title": "install_snapshot_bps",
     "type": "graph",
     "description": "安装快照的数据流量",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "raft_install_snapshot_bps{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "raft_storage_append_entries_latency {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "线程指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "bthread_worker_count",
     "type": "singlestat",
     "description": "chunkserver上bthread worker的数量",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "bthread_worker_count{instance=~\"$instance\"}",
       "legendFormat": "bthread_worker_count {{instance}}"
      }
     ]
    },
    {
     "title": "bthread_worker_usage",
     "type": "graph",
     "description": "chunkserver上正在被使用的工作线程个数",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bthread_worker_usage{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "bthread_count {{instance}}"
      }
     ]
    },
    {
     "title": "bthread_count",
     "type": "graph",
     "description": "chunkserver上bthread的数量",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bthread_count{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "bthread_count {{instance}}"
      }
     ]
    },
    {
     "title": "bthread_execq",
     "type": "graph",
     "description": "chunkserver上execution queue的数量",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "bthread_execq_count{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "bthread_execq_count {{instance}}"
      },
      {
       "expr": "bthread_execq_active_count{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": "bthread_execq_active_count {{instance}}"
      },
      {
       "expr": "bthread_execq_running_task_count{instance=~\"([[ip:pipe]]):[[port:regex]]\"}",
       "legendFormat": " bthread_execq_running_task_count {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}