{
 "title": "Etcd",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "主机", "query": "etcd_server_has_leader" }
  ]
 },
 "panels": [
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Etcd has a leader?",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "max(etcd_server_has_leader)" }
     ]
    },
    {
     "title": "The number of leader changes seen",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(etcd_server_leader_changes_seen_total)"
      }
     ]
    },
    {
     "title": "The total number of failed proposals seen",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(etcd_server_leader_changes_seen_total)"
      }
     ]
    },
    {
     "title": "Proposals Committed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "etcd_server_proposals_committed_total{instance=~\"$instance\"}",
       "legendFormat": "etcd_server_proposals_committed_total"
      },
      {
       "expr": "etcd_server_proposals_applied_total{instance=~\"$instance\"}",
       "legendFormat": "etcd_server_proposals_applied_total"
      },
      {
       "expr": "etcd_server_proposals_pending{instance=~\"$instance\"}",
       "legendFormat": "etcd_server_proposals_pending"
      },
      {
       "expr": "etcd_server_proposals_failed_total{instance=~\"$instance\"}",
       "legendFormat": "etcd_server_proposals_failed_total"
      }
     ]
    },
    {
     "title": "DB Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} DB Size"
      }
     ]
    },
    {
     "title": "Snapshot Duration",
     "type": "graph",
     "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum[1m]))",
       "legendFormat": "The total latency distributions of save called by snapshot"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Fsync Duration Sec Quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "\nhistogram_quantile(1, \n  sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le)\n)",
       "legendFormat": "quantile=1"
      },
      {
       "expr": "\nhistogram_quantile(0.99, \n  sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le)\n)",
       "legendFormat": "quantile=0.99"
      },
      {
       "expr": "\nhistogram_quantile(0.75, \n  sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le)\n)",
       "legendFormat": "quantile=0.75"
      },
      {
       "expr": "\nhistogram_quantile(0.50, \n  sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le)\n)",
       "legendFormat": "quantile=0.50"
      },
      {
       "expr": "\nhistogram_quantile(0.25, \n  sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le)\n)",
       "legendFormat": "quantile=0.25"
      },
      {
       "expr": "rate(etcd_disk_wal_fsync_duration_seconds_sum{instance=~\"$instance\"}[5m]) / rate(etcd_disk_wal_fsync_duration_seconds_count{instance=~\"$instance\"}[5m])",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Increamental Snapshot Commit Duration Sec Quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,\n  sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le)\n)",
       "legendFormat": "quantile=1"
      },
      {
       "expr": "histogram_quantile(0.99,\n  sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (instance,le)\n)",
       "legendFormat": "quantile=0.99"
      },
      {
       "expr": "histogram_quantile(0.75,\n  sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (instance,le)\n)",
       "legendFormat": "quantile=0.75"
      },
      {
       "expr": "histogram_quantile(0.50,\n  sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (instance,le)\n)",
       "legendFormat": "quantile=0.50"
      },
      {
       "expr": "histogram_quantile(0.25,\n  sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (instance,le)\n)",
       "legendFormat": "quantile=0.25"
      },
      {
       "expr": "rate(etcd_disk_backend_commit_duration_seconds_sum{instance=~\"$instance\"}[5m]) / rate(etcd_disk_backend_commit_duration_seconds_count{instance=\"$instance\"}[5m])",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "NetWork",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peer Traffic Out",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_network_peer_sent_bytes_total{instance=~\"$instance\"}[1m])) by (To)"
      }
     ]
    },
    {
     "title": "Peer Traffic In",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_network_peer_received_bytes_total{instance=~\"$instance\"}[1m])) by (From)",
       "legendFormat": "{{instance}} receive from {{From}}"
      }
     ]
    },
    {
     "title": "Sent Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "etcd_network_peer_sent_bytes_total{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Sent Failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "etcd_network_peer_sent_failures_total{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Received Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "etcd_network_peer_received_bytes_total{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Receive Failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "etcd_network_peer_received_failures_total{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Round Trip Time Quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,\n  sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{instance=~\"$instance\"}[1m])) by (To,le)\n)",
       "legendFormat": "to={{To}}, quantile=1"
      },
      {
       "expr": "histogram_quantile(0.99,\n  sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{instance=~\"$instance\"}[1m])) by (To,le)\n)",
       "legendFormat": "to={{To}}, quantile=0.99"
      },
      {
       "expr": "histogram_quantile(0.75,\n  sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{instance=~\"$instance\"}[1m])) by (To,le)\n)",
       "legendFormat": "to={{To}}, quantile=0.75"
      },
      {
       "expr": "histogram_quantile(0.50,\n  sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{instance=~\"$instance\"}[1m])) by (To,le)\n)",
       "legendFormat": "to={{To}}, quantile=0.50"
      },
      {
       "expr": "histogram_quantile(0.25,\n  sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{instance=~\"$instance\"}[1m])) by (To,le)\n)",
       "legendFormat": "to={{To}}, quantile=0.25"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[1m]))",
       "legendFormat": "RPC Rate"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[1m]))",
       "legendFormat": "RPC Failed Rate"
      }
     ]
    },
    {
     "title": "Active Streams",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
       "legendFormat": "Lease Streams"
      },
      {
       "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
       "legendFormat": "Watch Streams"
      }
     ]
    },
    {
     "title": "Client Traffic In",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} Client Traffic In"
      }
     ]
    },
    {
     "title": "Client Traffic Out",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} Client Traffic Out"
      }
     ]
    },
    {
     "title": "RPC Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grpc_server_handled_total{instance=~\"$instance\"}",
       "legendFormat": "method={{grpc_method}}, service={{grpc_service}}, type={{grpc_type}}"
      }
     ]
    },
    {
     "title": "Error RPC Requst",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(grpc_server_handled_total{instance=~\"$instance\",grpc_code!=\"OK\"}) by (grpc_service)"
      }
     ]
    },
    {
     "title": "Different RPC Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{instance=~\"$instance\"}[10s])) by (grpc_service)"
      }
     ]
    },
    {
     "title": "Avg Rep-Stream Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_msg_sent_total{instance=~\"$instance\",grpc_type=\"server_stream\"}[1m])) by (grpc_service)\n /\nsum(rate(grpc_server_started_total{instance=~\"$instance\",grpc_type=\"server_stream\"}[1m])) by (grpc_service)"
      }
     ]
    },
    {
     "title": "RPC Lantency Quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, \n  sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\"}[5m])) by (grpc_service,le)\n)",
       "legendFormat": "grpc_service={{grpc_service}}, quantile=1"
      },
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\"}[5m])) by (grpc_service,le)\n)",
       "legendFormat": "grpc_service={{grpc_service}}, quantile=0.99"
      },
      {
       "expr": "histogram_quantile(0.75, \n  sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\"}[5m])) by (grpc_service,le)\n)",
       "legendFormat": "grpc_service={{grpc_service}}, quantile=0.75"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\"}[5m])) by (grpc_service,le)\n)",
       "legendFormat": "grpc_service={{grpc_service}}, quantile=0.50"
      },
      {
       "expr": "histogram_quantile(0.25, \n  sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\"}[5m])) by (grpc_service,le)\n)",
       "legendFormat": "grpc_service={{grpc_service}}, quantile=0.25"
      }
     ]
    },
    {
     "title": "Slow Unary Queries (>250ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\",grpc_type=\"unary\",le=\"0.25\"}[5m])) by (grpc_service)\n / \nsum(rate(grpc_server_handling_seconds_count{instance=~\"$instance\",grpc_type=\"unary\"}[5m])) by (grpc_service)\n) * 100.0"
      }
     ]
    }
   ]
  }
 ]
}