{
 "title": "SnapshotCloneServer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "主机",
    "query": "{__name__=~\"snapshotcloneserver_.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "进程资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "进程运行时间",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cpu使用率",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "任务信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "快照任务表",
   "type": "table",
   "description": "当前快照任务的信息",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{__name__=~\"snapshotcloneserver_snapshot_info_metric.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "克隆任务表",
   "type": "table",
   "description": "当前克隆任务的信息",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{__name__=~\"snapshotcloneserver_clone_info_metric.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "快照数量统计",
   "type": "graph",
   "description": "快照数量统计",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"snapshotcloneserver_snapshot_metric_.*\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  },
  {
   "title": "克隆数量统计",
   "type": "graph",
   "description": "快照数量统计",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"snapshotcloneserver_clone_metric_.*\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  }
 ]
}