#!/bin/bash

set -e

chown -R root:root /data/nebd
chown -R root:root /data/log/nebd

chmod -R 777 /data/nebd
chmod -R 777 /data/log/nebd

cp /usr/bin/nebd-daemon /etc/init.d
update-rc.d nebd-daemon defaults

exit 0
