---
  - name: sync precheck
    synchronize: >
      src={{ playbook_dir }}/util
      dest=/tmp
      dest_port={{ ansible_ssh_port }}

  - name: precheck for {{ project_name }}
    shell: bash /tmp/util/precheck.sh -t {{ project_name }}
    register: precheck
