---
- include: core.yml
  tags:
    - core

- include: check.yml
  tags:
    - check
    - start
    - restart
    - mount

- include: config.yml
  tags:
    - config

- include: start.yml
  tags:
    - start

- include: restart.yml
  tags:
    - restart

- include: stop.yml
  tags:
    - stop

- include: status.yml
  tags:
    - status

- include: clean.yml
  tags:
    - clean
