{
 "title": "cluster",
 "description": "Curvefs cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "fsName",
    "label": "fsName",
    "query": {
     "query": "{__name__=~\"fs_usage_info_fs_.*_used\",job=\"mds\"}"
    }
   },
   {
    "name": "fsId",
    "label": "fsId",
    "query": {
     "query": "{__name__=~\"topology_fs_id_[0-9]*_inode_num\",job=\"mds\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "fs usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "fs used",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{__name__=~\"fs_usage_info_fs_[[fsName:regex]]_used\", job=\"mds\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cluster total used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum({__name__=~\"fs_usage_info_fs_[[fsName:regex]]_used\",job=\"mds\"})"
      }
     ]
    },
    {
     "title": "fs used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"fs_usage_info_fs_[[fsName:regex]]_used\", job=\"mds\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "inode_num_by_type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_fs_id_[[fsId:regex]]_.*inode_num\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "cluster inode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"topology_fs_id_[0-9]*_inode_num\",job=\"mds\"})"
      }
     ]
    },
    {
     "title": "cluster file inode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"topology_.*_type_file_inode_num\",job=\"mds\"})"
      }
     ]
    },
    {
     "title": "cluster directory inode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"topology_.*_type_directory_inode_num\",job=\"mds\"})"
      }
     ]
    },
    {
     "title": "cluster sym_link inode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"topology_.*_type_sym_link_inode_num\",job=\"mds\"})"
      }
     ]
    },
    {
     "title": "cluster s3 inode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"topology_.*_type_s3_inode_num\",job=\"mds\"})"
      }
     ]
    }
   ]
  }
 ]
}