{
 "title": "mds",
 "description": "Curvefs mds server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pool",
    "query": {
     "query": "{__name__=~\"topology_metric_pool_.*_metaserver_num\",job=\"mds\"}"
    }
   },
   {
    "name": "instance",
    "label": "Addr",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"mds\"}"
    }
   },
   {
    "name": "metaserver",
    "label": "metaserverId",
    "query": {
     "query": "{__name__=~\"topology_metric_metaserver_id_.*_copyset_num\",job=\"mds\"}"
    }
   },
   {
    "name": "fs",
    "label": "fsId",
    "query": {
     "query": "{__name__=~\"topology_fs_id_[0-9]*_inode_num\",job=\"mds\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "process usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_resident{instance=~\"$instance\"}",
     "legendFormat": "process_memory_resident {{instance}}"
    },
    {
     "expr": "process_memory_virtual{instance=~\"$instance\"}",
     "legendFormat": "process_memory_virtual {{instance}}"
    },
    {
     "expr": "process_memory_shared{instance=~\"$instance\"}",
     "legendFormat": "process_memory_shared {{instance}}"
    }
   ]
  },
  {
   "title": "process cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage {{instance}}"
    },
    {
     "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_system {{instance}}"
    },
    {
     "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_user {{instance}}"
    }
   ]
  },
  { "title": "mds config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "mds config",
   "type": "table",
   "description": "mds的配置",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_mds_config.*\", job=\"mds\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "pool metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "metaserver_num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_pool_[[pool:regex]]_metaserver_num\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "copyset_num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_pool_[[pool:regex]]_copyset_num\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "partition_num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_pool_[[pool:regex]]_partition_num\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "inode_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_pool_[[pool:regex]]_inode_num\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "dentry_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_pool_[[pool:regex]]_dentry_num\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "memory_threshold",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_pool_[[pool:regex]]_memory_threshold\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "memory_used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_pool_[[pool:regex]]_memory_used\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "disk_threshold",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_pool_[[pool:regex]]_disk_threshold\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "disk_used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_pool_[[pool:regex]]_disk_used\",job=\"mds\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "metaserver resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "copyset_num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_copyset_num\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "partition_num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_partition_num\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "leader_num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_leader_num\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "memory_threshold",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_memory_threshold\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "memory_used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_memory_used\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "memory_min_require",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_memory_min_require\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "disk_threshold",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_disk_threshold\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "disk_used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_disk_used\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "disk_min_require",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_disk_min_require\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "scatterwidth",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]]_scatterwidth\",job=\"mds\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "fs metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "fs_mount_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"fs_.*_mount_count\",job=\"mds\"}"
      }
     ]
    },
    {
     "title": "inode_num_by_type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"topology_fs_id_[[fs:regex]]_.*inode_num\",job=\"mds\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "schedule metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "schedule_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"mds_scheduler_metric.*\",job=\"mds\"}"
      }
     ]
    }
   ]
  }
 ]
}