{
 "title": "metaserver",
 "description": "Curvefs mds server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Addr",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"metaserver\"}"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "{__name__=~\"op_apply_pool_.*_copyset.*create_inode_count\", job=\"metaserver\"}"
    }
   },
   {
    "name": "copyset",
    "label": "copyset",
    "query": {
     "query": "{__name__=~\".*copyset_.*_create_inode_count\", job=\"metaserver\"}"
    }
   },
   {
    "name": "quantile",
    "label": "latency_quantile",
    "query": {
     "query": "{__name__=~\".*(latency_[0-9]*|latency)\", job=\"metaserver\"}"
    }
   },
   {
    "name": "op",
    "label": "op",
    "query": {
     "query": "{__name__=~\".*curvefs_metaserver_meta_server_service_.*_qps\", job=\"metaserver\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "process usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_resident{instance=~\"$instance\"}",
     "legendFormat": "process_memory_resident {{hostname}}"
    },
    {
     "expr": "process_memory_virtual{instance=~\"$instance\"}",
     "legendFormat": "process_memory_virtual {{hostname}}"
    },
    {
     "expr": "process_memory_shared{instance=~\"$instance\"}",
     "legendFormat": "process_memory_shared {{hostname}}"
    }
   ]
  },
  {
   "title": "process cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage {{hostname}}"
    },
    {
     "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_system {{hostname}}"
    },
    {
     "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_user {{hostname}}"
    }
   ]
  },
  { "title": "metaserver config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "metaserver config",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_metaserver_config.*\", job=\"metaserver\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "service total performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "total_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".*curvefs_metaserver_meta_server_service.*_qps\",job=\"metaserver\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "total_error_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".*curvefs_metaserver_meta_server_service.*_error\",job=\"metaserver\", instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "service latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "create_inode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_create_inode_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "create_dentry",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_create_dentry_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "delete_inode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_delete_inode_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "delete_dentry",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_delete_dentry_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "get_inode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_get_inode_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "get_dentry",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_get_dentry_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "batch_get_inode_attr",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_batch_get_inode_attr_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "list_dentry",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_list_dentry_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "update_inode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_update_inode_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "batch_get_xattr",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_batch_get_xattr_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "prepare_rename_tx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_prepare_rename_tx_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "get_or_modify_s3_chunk_info",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_get_or_modify_s3_chunk_info_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "create_partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_create_partition_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "delete_partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_delete_partition_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "get_volume_extent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_get_volume_extent_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "update_volume_extent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*curvefs_metaserver_meta_server_service_update_volume_extent_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "raft op metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "op_qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "qps" } },
     "yaxes": [
      { "format": "qps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"op_apply_pool_[[pool:regex]]_copyset_[[copyset:regex]]_[[op:regex]]_qps\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "op_rps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"op_apply_pool_[[pool:regex]]_copyset_[[copyset:regex]]_[[op:regex]]_rps\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "op_eps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "yaxes": [
      { "format": "eps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"op_apply_pool_[[pool:regex]]_copyset_[[copyset:regex]]_[[op:regex]]_eps\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "op_apply_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"op_apply_pool_[[pool:regex]]_copyset_[[copyset:regex]]_[[op:regex]]_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "op_apply_execute_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"op_apply_pool_[[pool:regex]]_copyset_[[copyset:regex]]_[[op:regex]]_execute_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "op_apply_wait_in_queue_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"op_apply_pool_[[pool:regex]]_copyset_[[copyset:regex]]_[[op:regex]]_wait_in_queue_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "raft snapshot metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "copyset_snapshot_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_snapshot_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "copyset_snapshot_error_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_snapshot_error_count\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "copyset_snapshot_flying_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copyset_snapshot_flying_count\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "rocksdb metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "rocksdb_flushing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rocksdb_flushing\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rocksdb_flush_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rocksdb_flush_[[quantile:regex]]\", job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rocksdb_compacting",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rocksdb_compacting\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rocksdb_compaction_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rocksdb_compaction_[[quantile:regex]]\", job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rocksdb_sealed_memtable",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rocksdb_sealed_memtable\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rocksdb_delayed_write",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rocksdb_delayed_write\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rocksdb_stopped_write",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"rocksdb_stopped_write\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "raft builtin metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "raft_apply_tasks_batch_counter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_apply_tasks_batch_avg_counter\",job=\"metaserver\", instance=~\"$instance\"}"
      },
      {
       "expr": "{__name__=~\"raft_apply_tasks_batch_counter_.*\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_send_entries_batch_counter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_send_entries_batch_avg_counter\",job=\"metaserver\", instance=~\"$instance\"}"
      },
      {
       "expr": "{__name__=~\"raft_send_entries_batch_counter_.*\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_send_entries_qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "qps" } },
     "yaxes": [
      { "format": "qps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_send_entries_qps\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_send_entries_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_send_entries_[[quantile:regex]]\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_service_append_entries_qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "qps" } },
     "yaxes": [
      { "format": "qps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*raft_service_append_entries_qps\",job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_service_append_entries_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*raft_service_append_entries\", job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_storage_append_entries_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*raft_storage_append_entries_[[quantile:regex]]\", job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_storage_append_entries_normalized_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_storage_append_entries_normalized_[[quantile:regex]]\", job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_storage_flush_batch_counter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_storage_flush_batch_avg_counter\", job=\"metaserver\", instance=~\"$instance\"}"
      },
      {
       "expr": "{__name__=~\"raft_storage_flush_batch_counter_[[quantile:regex]]\", job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_num_log_entries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"raft_num_log_entries\", job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "raft_service_install_snapshot_qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "qps" } },
     "yaxes": [
      { "format": "qps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\".*raft_service_install_snapshot_qps\", job=\"metaserver\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}