.PHONY: build curve-sdk

curve-sdk:
	docker build --target  curve-sdk-release1.5 -t opencurvedocker/curve-base:curve-sdk-debian11-release1.5 .

build:
	docker build --target  curve-tgt-release1.5 -t opencurvedocker/curve-base:curve-tgt-debian11-release1.5 .
