.PHONY: build

curve-sdk:
	docker build --target  curve-tgt -t opencurvedocker/curve-base:curve-tgt-debian11 .

build:
	docker build --target  curve-tgt -t opencurvedocker/curve-base:curve-tgt-debian11 .
