{
 "title": "client",
 "description": "Curvefs client",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Addr",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"client\"}"
    }
   },
   {
    "name": "fs",
    "label": "fsname",
    "query": {
     "query": "{__name__=~\"curvefs_s3_.*_adaptor_write_bps\", job=\"client\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "process usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_resident{instance=~\"$instance\"}",
     "legendFormat": "process_memory_resident {{instance}}"
    },
    {
     "expr": "process_memory_virtual{instance=~\"$instance\"}",
     "legendFormat": "process_memory_virtual {{instance}}"
    },
    {
     "expr": "process_memory_shared{instance=~\"$instance\"}",
     "legendFormat": "process_memory_shared {{instance}}"
    }
   ]
  },
  {
   "title": "process cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage {{instance}}"
    },
    {
     "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_system {{instance}}"
    },
    {
     "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_user {{instance}}"
    }
   ]
  },
  { "title": " r/w performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "read_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*read_qps.*\"}"
    }
   ]
  },
  {
   "title": "write_qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*write_qps.*\"}"
    }
   ]
  },
  {
   "title": "read_bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*read_bps.*\"}"
    }
   ]
  },
  {
   "title": "write_bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*write_bps.*\"}"
    }
   ]
  },
  {
   "title": "read_eps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*read_eps.*\"}"
    }
   ]
  },
  {
   "title": "write_eps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*write_eps.*\"}"
    }
   ]
  },
  {
   "title": "read_rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*read_rps.*\"}"
    }
   ]
  },
  {
   "title": "write_rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*write_rps.*\"}"
    }
   ]
  },
  {
   "title": "read_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*read.*latency.*\"}"
    }
   ]
  },
  {
   "title": "write_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs.*[[fs:regex]].*write.*latency.*\"}"
    }
   ]
  },
  { "title": "mds client latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "mds_clinet_bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_mds_client.*bps.*\"}"
    }
   ]
  },
  {
   "title": "mds_clinet_eps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_mds_client.*eps.*\"}"
    }
   ]
  },
  {
   "title": "mds_clinet_qps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_mds_client.*qps.*\"}"
    }
   ]
  },
  {
   "title": "mds_clinet_rps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_mds_client.*rps.*\"}"
    }
   ]
  },
  {
   "title": "mds_clinet_latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_mds_client.*latency.*\"}"
    }
   ]
  },
  { "title": "metaserver client latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "metaserver_clinet_bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_metaserver_client.*bps.*\"}"
    }
   ]
  },
  {
   "title": "metaserver_clinet_eps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_metaserver_client.*eps.*\"}"
    }
   ]
  },
  {
   "title": "metaserver_clinet_qps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_metaserver_client.*qps.*\"}"
    }
   ]
  },
  {
   "title": "metaserver_clinet_rps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_metaserver_client.*rps.*\"}"
    }
   ]
  },
  {
   "title": "metaserver_client_latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"curvefs_metaserver_client.*latency.*\"}"
    }
   ]
  }
 ]
}