{
 "title": "mds",
 "description": "Curvefs mds server",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Addr",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"mds\"}"
    }
   },
   {
    "name": "metaserver",
    "label": "metaserverId",
    "query": {
     "query": "{__name__=~\"topology_metric_metaserver_id_.*_copyset_num\",job=\"mds\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_memory_resident{instance=~\"$instance\"}",
       "legendFormat": "process_memory_resident {{instance}}"
      },
      {
       "expr": "process_memory_virtual{instance=~\"$instance\"}",
       "legendFormat": "process_memory_virtual {{instance}}"
      },
      {
       "expr": "process_memory_shared{instance=~\"$instance\"}",
       "legendFormat": "process_memory_shared {{instance}}"
      }
     ]
    },
    {
     "title": "process cpu usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage {{instance}}"
      },
      {
       "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_system {{instance}}"
      },
      {
       "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_user {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "metaserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "topology",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{__name__=~\"topology_metric_metaserver_id_[[metaserver:regex]].*\",job=\"mds\"}"
    }
   ]
  }
 ]
}