{
 "title": "metaserver",
 "description": "Curvefs mds server",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Addr",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"metaserver\"}"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"metaserver\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "process usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_resident{instance=~\"$instance\"}",
     "legendFormat": "process_memory_resident {{hostname}}"
    },
    {
     "expr": "process_memory_virtual{instance=~\"$instance\"}",
     "legendFormat": "process_memory_virtual {{hostname}}"
    },
    {
     "expr": "process_memory_shared{instance=~\"$instance\"}",
     "legendFormat": "process_memory_shared {{hostname}}"
    }
   ]
  },
  {
   "title": "process cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage {{hostname}}"
    },
    {
     "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_system {{hostname}}"
    },
    {
     "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_user {{hostname}}"
    }
   ]
  },
  { "title": "latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*latency.*\",job=\"metaserver\"}"
    }
   ]
  }
 ]
}