---
#
#  Copyright (c) 2020 NetEase Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

- name: install libunwind
  vars:
    lib_name: libunwind
    download_url: "{{ libunwind_download_url }}"
  include_tasks: install_lib_with_source_code.yml

- name: install libuuid
  include_tasks: install_libuuid.yml

- name: install snapshotcloneserver bin
  vars:
    remote_dir_name: "{{ snapshotcloneserver_bin_dir }}"
    local_file_path: "{{ local_snapshotcloneserver_package_path }}/bin/"
    file_mode: 0755
  include_tasks: copy_file_to_remote.yml

- name: install snapshotcloneserver lib
  vars:
    remote_dir_name: "{{ snapshotcloneserver_lib_dir}}"
    local_file_path: "{{ local_snapshotcloneserver_package_path }}/lib/"
    file_mode: 0644
  include_tasks: copy_file_to_remote.yml

- name: generate snapshot-daemon.sh
  template: src=snapshot-daemon.sh.j2 dest={{ deploy_dir }}/snapshot-daemon.sh mode=0755