---
#
#  Copyright (c) 2020 NetEase Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

- name: determine if lib installed
  ignore_errors: true
  shell: /sbin/ldconfig -p | grep {{ lib_name }}
  register: ldconfig_res

- name: set lib_installed
  set_fact:
    lib_installed: true
  when: ldconfig_res.stdout != ""

- name: install lib when not installed
  block:
    - name: download lib
      get_url:
        url: "{{ download_url }}"
        dest: "{{ lib_download_dir }}"
        validate_certs: no
        timeout: 60
      register: get_url_result
      until: not get_url_result.failed
      retries: 5
      delay: 3

    - name: unarchive lib
      unarchive:
        remote_src: true
        list_files: true
        src: "{{ get_url_result.dest }}"
        dest: "{{ lib_download_dir }}"
      register: unarchive_result
    
    - name: get unarcive dir
      shell: echo "{{ get_url_result.dest }}" | awk -F "." '{print $1}'

    - name: install lib
      shell: >
          chdir="{{ lib_download_dir }}/{{ unarchive_result.files[0] }}"
          ./configure && make && sudo make install
  when: not lib_installed
