# etcd
# ├── conf
# │   └── etcd.conf
# ├── logs
# │   └── etcd.pid
# ├── sbin
# │   ├── servicectl
#  |  ├── etcd
# │   └── etcdctl
# └── lib
#     └── etcd_lib.so

project_name: "etcd"
project_home: "{{ curvefs_project_home }}"
project_root_src: "{{ playbook_dir }}/projects/etcd"
project_root_dest: "{{ project_home }}/etcd"
project_log_root: "{{ curvefs_project_log_home }}/etcd"
project_config_src: "{{ playbook_dir | dirname }}/conf"
project_config_dsv: ": "
project_core_method: "{{ curvefs_core_method }}"
project_start_with_deamon: True
project_daemon: "{{ project_start_with_deamon | ternary('--daemon', '') }}"
project_listen_port: "{{ curvefs_etcd_listen_client_port }}"
project_wait_service_timeout: "{{ curvefs_wait_service_timeout }}"

project_templates:
  - etcd.conf

project_directorys:
  - "{{ project_root_dest }}"
  - "{{ project_log_root }}"
  - "{{ curvefs_etcd_data_dir }}"
  - "{{ curvefs_etcd_wal_dir }}"
