---
#
#  Copyright (c) 2020 NetEase Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

- name: generate signature
  include_tasks: "include/generate_signature.yml"

- name: get all host in cluster
  vars:
    all_host_list:
  include_tasks: "include/get_all_host_in_nss_cluster.yml"

- name: check if all host in group in nss cluster
  vars:
    member: "{{ item }}"
    list: "{{ all_host_list }}"
  include_tasks: "include/check_if_member_in_list.yml"
  with_items:
    "{{ group_hosts }}"

- name: get all monitor items in cluster from nss
  vars:
    monitor_items:
  include_tasks: "include/get_cluster_monitor_items_from_nss.yml"

- name: check if all monitor items set in nss
  vars:
    member: "{{ item }}"
    list: "{{ monitor_items }}"
  include_tasks: "include/check_if_member_in_list.yml"
  with_items:
    "{{ expected_monitor_items }}"

- name: get all alarm rules in cluster from nss
  vars:
    alarm_rules:
  include_tasks: "include/get_cluster_alarm_rules_from_nss.yml"

- name: check if all monitor items set in nss
  vars:
    member: "{{ item }}"
    list: "{{ alarm_rules }}"
  include_tasks: "include/check_if_member_in_list.yml"
  with_items:
    "{{ expected_alarm_rules }}"

