cc_test(
    name = "common-test",
    srcs = glob([
        "task_thread_pool_test.cpp",
    ]),
    deps = [
        "//src/common:curve_common",
        "//test/utils:test-utils",
        "@com_google_googletest//:gtest_main",
    ],
)
