cc_library(
    name = "nameserver2_mock",
    hdrs = glob(["*.h"]),
    deps = [
        "//src/mds/topology:topology",
        "//src/mds/nameserver2:nameserver2",
    ],
    visibility = ["//visibility:public"],
)
