cc_library(
    name = "chunkserver-sfsmock-lib",
    srcs = [
        "sfsMock.cpp",
        "sfsMock.h",
    ],
    linkopts = ([
        "-pthread",
        "-std=c++11",
    ]),
    visibility = ["//visibility:public"],
)
