cc_library(
    name = "test_utils_lib",
    srcs = glob([
        "*.h",
        "*.cpp"
    ]),
    hdrs = glob(["*.h"]),
    deps = [
        "//src/common:nebd_common",
    ],
    visibility = ["//visibility:public"],
)