TESTS_EXTRA = \
	tests/test.h \
	tests/drv_init_all.c \
	tests/startup.c \
	tests/sysio-run-start.c \
	tests/test_chown.c \
	tests/test_copy.c \
	tests/test_fcntl_lock.c \
	tests/test_getcwd.c \
	tests/test_link.c \
	tests/test_list.c \
	tests/test_mkdir.c \
	tests/test_mknod.c \
	tests/test_path.c \
	tests/test_stddir.c \
	tests/test_regions.c \
	tests/test_rename.c \
	tests/test_stats.c \
	tests/test_statvfs.c \
	tests/test_stddir.c \
	tests/test_symlink.c \
	tests/test_unlink.c \
	tests/test_fhichmod.c \
	tests/test_fhicreate.c \
	tests/test_fhilink.c \
	tests/test_fhilist.c \
	tests/test_fhimkdir.c \
	tests/test_fhipath.c \
	tests/test_fhirename.c \
	tests/test_fhirmdir.c \
	tests/test_fhisymlink.c \
	tests/test_fhitrunc.c \
	tests/test_fhiunlink.c \
	tests/curvefs_mount.cpp \
	tests/curvefs_startup.cpp \
	tests/curvefs_test.cpp \
	tests/curvefs_test.h \
	tests/Makefile.am tests/Makefile.in tests/module.mk
