cc_binary(
        name = "curvefsTool",
        srcs = ["curvefs.cpp"],
        deps = ["//proto:topology_cc_proto",
                "//external:gflags",
                "//src/mds/common:mds_common",
                "//external:glog",
                "//external:brpc"]
        )
