cc_binary(
    name = "nebd_common_unittest",
    srcs = glob([
        "*.cpp",
    ]),
    deps = [
        "//external:gflags",
        "//nebd/src/common:nebd_common",
        "//src/common:curve_common",
        "@com_google_googletest//:gtest_main",
    ],
)
