name: Static Checker

on:
  pull_request

jobs:
  cppcheck:
    name: CppCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: chmorgan/cppcheck-action@v1.4
        with:
          enable: all
          std: c++11
          inconclusive: disable
          output_file: ./cppcheck_report.txt
          other_options: "-j4 --suppressions-list=util/cppcheck/cppcheck.suppressions --error-exitcode=1 -itest -icurvefs/test -inebd/test -inbd/test -icurvefs_python -icurvesnapshot_python -ithirdparties"

      - name: Show cppcheck report
        if: failure()
        run: |
          cat ./cppcheck_report.txt
