name: cppcheck-action
on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - uses: deep5050/cppcheck-action@main 
      - uses: actions/upload-artifact@v3
        with:
          name: cppcheck
          path: cppcheck_report.txt
