---
#
#  Copyright (c) 2020 NetEase Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# The rolling update playbook of Curve

# 滚动升级chunkserver

# 1. 更新各节点上的配置
- name: update config
  hosts: chunkservers
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: "{{ sudo_user }}"
  become_flags: -iu {{ sudo_user }}
  tags:
    - update_config

  roles:
    - { role: generate_config, template_name: chunkserver.conf, conf_path: "{{ chunkserver_conf_path }}" }
    - { role: generate_config, template_name: client.conf, conf_path: "{{ chunkserver_client_config_path }}" }
    - { role: generate_config, template_name: s3.conf, conf_path: "{{ chunkserver_s3_config_path }}" }

# 2. 更新各节点上的包
- name: update package
  hosts: chunkservers
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: "{{ sudo_user }}"
  become_flags: -iu {{ sudo_user }}
  tags:
    - update_package

  tasks:
    - vars:
        update_component: "curve-chunkserver={{ cs_package_version }}"
      include_tasks: "common_tasks/update_package.yml"

# 3、逐个重启chunkserver，每重启完一个需要等待copyset健康
#    继续操作下一个的的时候还需要一个命令行交互确认
- name: restart chunkserver and wait healthy
  hosts: chunkservers
  any_errors_fatal: true
  gather_facts: no
  serial: 1
  become: yes
  become_user: "{{ sudo_user }}"
  become_flags: -iu {{ sudo_user }}
  tags:
    - restart

  pre_tasks:
    - pause:
        prompt: "Confirm restart chunkserver in {{ inventory_hostname }}. ENTER to continue or CTRL-C A to quit"
      when: need_confirm
    - vars:
        package_version: "{{ cs_package_version }}"
        software_version:
      include_tasks: "common_tasks/get_software_version_from_package_version.yml"

  roles:
    - { role: restart_service, service_name: chunkserver, expected_curve_version: "{{ software_version }}",
        command_need_sudo: "{{ chunkserver_need_sudo }}"}

  tasks:
    - include_tasks: "common_tasks/wait_copysets_status_healthy.yml"
