---
# Copyright 2020 NetEase, Inc.
# The rolling update playbook of Curve

# 滚动升级snapshotclone

# 1. 更新各节点上的配置
- name: update config
  hosts: snapshotclone
  gather_facts: no
  any_errors_fatal: true
  become: true
  become_user: "{{ sudo_user }}"
  become_flags: -iu {{ sudo_user }}
  tags:
    - update_config
  roles:
    - { role: generate_config, template_name: snapshot_clone_server, conf_path: "{{ snapshot_config_path }}" }
    - { role: generate_config, template_name: s3, conf_path: "{{ snap_s3_config_path }}" }
    - { role: generate_config, template_name: client, conf_path: "{{ snap_client_config_path }}" }
    - { role: generate_config, template_name: snapshot_tools, conf_path: "{{ snap_tool_config_path }}" }

# 2. 更新各节点上的包和配置
- name: update package
  hosts: snapshotclone
  gather_facts: no
  any_errors_fatal: true
  become: true
  become_user: "{{ sudo_user }}"
  become_flags: -iu {{ sudo_user }}
  tags:
    - update_package

  tasks:
    - vars:
        update_component: "curve-snapshotcloneserver={{ snap_package_version }}"
      include_tasks: "common_tasks/update_package.yml"

# 3. 获取leader节点和follower节点
- name: set leader and follower list
  hosts: snapshotclone
  gather_facts: no
  serial: 1
  tags:
    - restart
  roles:
    - { role: set_leader_and_follower_list, service_name: snapshot }

# 4. 按顺序先升级follower节点，再升级leader节点
- name: update follower and leader server in sequence
  hosts: snapshot_servers_followers, snapshot_servers_leader
  any_errors_fatal: true
  gather_facts: no
  serial: 1
  become: true
  become_user: "{{ sudo_user }}"
  become_flags: -iu {{ sudo_user }}
  tags:
    - restart

  pre_tasks:
    - pause:
        prompt: "Confirm restart snapshotclone in {{ inventory_hostname }}. ENTER to continue or CTRL-C A to quit"
      when: need_confirm
    - vars:
        package_version: "{{ mds_package_version }}"
        software_version:
      include_tasks: "common_tasks/get_software_version_from_package_version.yml"

  # 重启snapshot clone
  roles:
    - { role: restart_service, service_name: snapshotclone, expected_curve_version: "{{ software_version }}" }
