---
#
#  Copyright (c) 2020 NetEase Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# The rolling update playbook of Curve

- name: check_ansible_version
  tags:
    - always
  import_playbook: check_ansible_version.yml

- name: prepare nebd
  hosts: client
  gather_facts: no
  any_errors_fatal: true
  become: "{{ sudo_or_not | bool }}"
  tags:
    - prepare
  roles:
    - { role: install_package, package_name: nebd, package_version: "{{ nebd_package_version }}",
            tags: ["install_package"] }
    - { role: generate_config, template_name: client.conf, conf_path: "{{ client_config_path }}", when: not update_config_with_puppet | bool }
    - { role: generate_config, template_name: nebd-client.conf, conf_path: "{{ nebd_client_config_path }}", when: not update_config_with_puppet | bool }
    - { role: generate_config, template_name: nebd-server.conf, conf_path: "{{ nebd_server_config_path }}", when: not update_config_with_puppet | bool }
  tasks:
    - name: update config with puppet
      include_tasks: "common_tasks/update_config_with_puppet.yml"
      when: update_config_with_puppet | bool

- name: restart nebd server
  hosts: client
  gather_facts: no
  any_errors_fatal: true
  tags:
    - restart

  pre_tasks:
    - pause:
        prompt: "Confirm restart nebd-server in {{ inventory_hostname }}. ENTER to continue or CTRL-C A to quit"
      when: need_confirm | bool
  roles:
    - { role: restart_service, service_name: nebd, expected_nebd_version: "{{ nebd_package_version }}",
        command_need_sudo: "{{ nebd_need_sudo | bool }}" }
